version: '3.0'

services:
  frontend: 
    container_name: badbankapp-frontend
    restart: always
    build: 
      context: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - api
  
  api:
    container_name: badbankapp-api
    restart: always
    build:
      context: backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/api
      - /backend/node_modules
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo
    restart: always
    container_name: badbankapp-mongodb
    volumes:
      - ./database:/data.db
    ports:
      - "27017:27017"
    